### ISSUE TITLE
script/eval.py

### ISSUE THREAD

**Issue by sho-asn** [superleesa/final_year_project#21]
@superleesa 
Do we need to use yml config for eval.py as well?

**Comment by sho-asn** [comment]
@superleesa 
I'm trying to evaluate the sft model though I shouldn't  change the location of eval.py?

**Comment by superleesa** [comment]
yeah i think we should use yml config for evaluation as well.

**Comment by superleesa** [comment]
for directory organization i will do it later on.

**Comment by sho-asn** [comment]
@superleesa 
All right
